#ifndef __EXTMEMLOADER_CONF_H_
#define __EXTMEMLOADER_CONF_H_

#include "extmemloader_init.h"
#include "stm32_extmem_conf.h"

#define STM32EXTLOADER_DEVICE_MEMORY_ID       EXTMEMORY_1
#define	STM32EXTLOADER_DEVICE_NAME            "W25Q64JV_Lumon"
#define STM32EXTLOADER_DEVICE_TYPE            3 // NOR_FLASH
#define	STM32EXTLOADER_DEVICE_ADDR            0x90000000
#define	STM32EXTLOADER_DEVICE_SIZE            0x800000   // 8 MBytes
#define	STM32EXTLOADER_DEVICE_SECTOR_NUMBERS  2048       // 2048 sectors of 4KB
#define	STM32EXTLOADER_DEVICE_SECTOR_SIZE     0x1000     // 4 KBytes sector size
#define	STM32EXTLOADER_DEVICE_PAGE_SIZE       0x100      // 256 Bytes page size
#define	STM32EXTLOADER_DEVICE_INITIAL_CONTENT 0xFF
#define STM32EXTLOADER_DEVICE_PAGE_TIMEOUT    10000
#define STM32EXTLOADER_DEVICE_SECTOR_TIMEOUT  6000

#endif /* __EXTMEMLOADER_CONF_H_ */
